# Configuration file for the classifier experiment

project:
  name: covid_xray_clf

model:
  base_model_name: &model_name mobilenet_v2
  dropout: 0.2
  fine_tune_at: 100
  num_channels: 3
  path_save: ../../Models

# Data
# Data take from:
#   Sultana A et al. A Real Time Method for Distinguishing COVID-19 Utilizing 2D-CNN 
#   and Transfer Learning. Sensors. 2023; 23(9):4458. https://doi.org/10.3390/s23094458 
data:
  path: ../../Data/COVID-19_CXR_Dataset_final
  url: https://drive.google.com/drive/folders/1RxA5TvT9OGS-3zURbzBiUoRJzT-9zd9L?usp=sharing
  val_split: 0.2
  test_split: 2
  augmentation:
    rotation: 0.2
    flip: 'horizontal'
    height_shift_range: 0.1
    shear_range: 0.1
    zoom_range: 0.1
    horizontal_flip: True
    fill_mode: nearest
  img_height: 299
  img_width: 299
  color: grayscale
  cache: True
  prefetch: True
  shuffle: 1000

train:
  # Parameters
  batch_size: 256
  lr: 0.0001
  optimizer: adam
  loss: categorical_crossentropy
  metrics: 
  - 'accuracy'
  epochs: 20
  epochs_finetune: 10
  fine_tune_at_perc: 80    # Default: 0, no fine-tuning
  lr_finetune: 0.00001
  mode_display: False

tb:
  # Tensorboard logs
  log_dir: tb_logs
  histogram_freq: 1
  profile_batch: 2
  # Early stopping
  early_stopping:
    monitor: val_loss
    patience: 5
  # Model checkpoint
  model_ckpt:
    ckpt_freq: 5
    ckpt_path: ckpts
    ckpt_monitor: val_accuracy
  # Reduce learning rate
  reduce_lr:
    monitor: val_loss
    factor: 0.2
    patience: 5
    min_lr: 0.000001   

general:
  display: True
  ai_framework: tf

runs:
  description:
  name: !join [ 'test' , '_', *model_name ]

  
